name: Static Analysis
on:
  push:
jobs:
  phpstsan:
    name: phpstan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          coverage: none
      - uses: ramsey/composer-install@v2
        with:
          composer-options: "--ignore-platform-reqs --optimize-autoloader"
      - name: Run PHPStan static analysis
        run: composer test:analysis
