name: 'CI'
on:
  push:
jobs:
  test:
    strategy:
      matrix:
        suite:
          - wpunit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1000
          submodules: recursive
      # ------------------------------------------------------------------------------
      # Checkout tric
      # ------------------------------------------------------------------------------
      - name: Checkout tric
        uses: actions/checkout@v2
        with:
          repository: the-events-calendar/tric
          ref: main
          path: tric
          fetch-depth: 1
      # ------------------------------------------------------------------------------
      # Prepare our composer cache directory
      # ------------------------------------------------------------------------------
      - name: Get Composer Cache Directory
        id: get-composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        id: composer-cache
        with:
          path: ${{ steps.get-composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      # ------------------------------------------------------------------------------
      # Initialize tric
      # ------------------------------------------------------------------------------
      - name: Set up tric env vars
        run: |
          echo "TRIC_BIN=${GITHUB_WORKSPACE}/tric/tric" >> $GITHUB_ENV
          echo "TRIC_WP_DIR=${GITHUB_WORKSPACE}/tric/_wordpress" >> $GITHUB_ENV
          echo "TRIC_WORDPRESS_DOCKERFILE=Dockerfile.base" >> $GITHUB_ENV
      - name: Set run context for tric
        run: echo "TRIC=1" >> $GITHUB_ENV && echo "CI=1" >> $GITHUB_ENV
      - name: Start ssh-agent
        run: |
          mkdir -p "${HOME}/.ssh";
          ssh-agent -a /tmp/ssh_agent.sock;
      - name: Export SSH_AUTH_SOCK env var
        run: echo "SSH_AUTH_SOCK=/tmp/ssh_agent.sock" >> $GITHUB_ENV
      - name: Set up tric for CI
        run: |
          cd ${GITHUB_WORKSPACE}/..
          ${TRIC_BIN} here
          ${TRIC_BIN} interactive off
          ${TRIC_BIN} build-prompt off
          ${TRIC_BIN} build-subdir off
          ${TRIC_BIN} xdebug off
          ${TRIC_BIN} debug on
          ${TRIC_BIN} info
          ${TRIC_BIN} config
      - name: Set up StellarWP Schema
        run: |
          ${TRIC_BIN} use schema
          ${TRIC_BIN} composer install --ignore-platform-reqs
      - name: Run suite tests
        run: ${TRIC_BIN} run ${{ matrix.suite }} --ext DotReporter
